- app/build.gradle
- build.gradle
> Closes #1470: Apply kotlin plugin before kapt.

- docs/telemetry.md
> Closes #123: remove incorrect/redundant info from telemetry docs

- CHANGELOG.md
- app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxWebView.kt
- app/src/main/java/org/mozilla/focus/browser/BrowserFragment.kt
- app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt
- app/src/main/java/org/mozilla/focus/iwebview/IWebView.kt
- app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
- app/src/main/java/org/mozilla/focus/widget/OnInterceptTouchEventFrameLayout.kt
- app/src/main/res/layout/fragment_browser.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/mozilla/focus/browser/FullscreenCallbacksTest.kt
- app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt
- docs/telemetry.md
> Closes #75: Add pinch gesture to exit fullscreen mode

- app/src/main/java/org/mozilla/focus/home/NavigationOverlayAnimations.kt
Review bottom-most commit only.
- Animations are hard to test
> Issue #117: Dynamically change nav overlay animation on screen size.

- build.gradle
- buildSrc/build.gradle.kts
Build changes only
Not user facing
> Closes #168: changes order of repos in build scripts

- CHANGELOG.md
- app/src/main/java/org/mozilla/focus/MainActivity.kt
- app/src/main/java/org/mozilla/focus/toolbar/BrowserAppBarLayoutController.kt
- app/src/test/java/org/mozilla/focus/toolbar/BrowserAppBarLayoutControllerTest.kt
> Closes #153: Remove TouchExploration...Listener in BrowserAppBarLayout

- README.md
- docs/device_reference.md
> Closes #177: Clarify recommended test devices/emulators.

- docs/telemetry.md
> Closes #173: Document telemetry session eccentricities.

- docs/telemetry.md
Changes documentation only
Changes documentation only
> No issue: fix telemetry formatting. Changes spacing only

- app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Closes #136: Import strings from FFTV

- build.gradle
> No issue: update detekt, ktlint

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-es-rMX/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
This fixes the bustage on master. This happened from a bad rebase.
> No issue: add back nav_close_hint.

- app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
- docs/telemetry.md
Telemetry is not tested at this time
> 151 track usage outside youtube

- .github/PULL_REQUEST_TEMPLATE
> No issue: update github PR template.

- .travis.yml
Let's us travis CI while we wait for TaskCluster set-up.
> No issue: update travis config to assemble, run tests.

- app/build.gradle
- app/src/androidTest/java/org/mozilla/focus/integration/home/HomeTileScreenshotStoreIntegrationTest.kt
- app/src/main/java/org/mozilla/focus/MainActivity.kt
- app/src/main/java/org/mozilla/focus/browser/HomeTileAdapter.kt
- app/src/main/java/org/mozilla/focus/browser/HomeTileGridNavigation.kt
- app/src/main/java/org/mozilla/focus/home/HomeTileScreenshotStore.kt
- app/src/main/java/org/mozilla/focus/home/NavigationOverlayFragment.kt
- app/src/main/java/org/mozilla/focus/toolbar/ProgressBarController.kt
- app/src/main/java/org/mozilla/focus/toolbar/ToolbarIntegration.kt
- app/src/main/java/org/mozilla/focus/utils/CoroutineScope.kt
- app/src/main/java/org/mozilla/focus/utils/publicsuffix/PublicSuffixKt.kt
- app/src/test/java/org/mozilla/focus/home/HomeTileScreenshotStoreUnitTest.kt
- app/src/test/java/org/mozilla/focus/utils/ActivityUiCoroutineScopeTest.kt
- app/src/test/java/org/mozilla/focus/utils/FragmentViewUiCoroutineScopeTest.kt
- build.gradle
[The official documentation]( https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#structured-concurrency-lifecycle-and-coroutine-parent-child-hierarchy) recommends using inheritance/implementation to create coroutineScopes wrapped around activities but instead I opted for composability.
The guide doesn't explain how to create a lifecycle around the fragment view lifecycle scope so I created my own.
- For new types, have 100% coverage, depending on who you ask ;)
> Closes #148: Upgrade to Kotlin 1.3

- CHANGELOG.md
- app/build.gradle
> No issue: bump version to v1.3

- .travis.yml
- app/build.gradle
- app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxWebView.kt
- app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java
- app/src/main/java/org/mozilla/focus/ext/Uri.kt
- app/src/main/java/org/mozilla/focus/home/HomeTilesManager.kt
- app/src/main/java/org/mozilla/focus/toolbar/ToolbarText.kt
- app/src/main/java/org/mozilla/focus/toolbar/UrlBoxBackgroundWithProgress.kt
- app/src/main/java/org/mozilla/focus/utils/ToastManager.kt
- app/src/main/java/org/mozilla/focus/widget/AccessibleGridLayoutManager.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/test/java/org/mozilla/focus/TestResource.kt
- app/src/test/java/org/mozilla/focus/ext/UriKtTest.kt
- app/src/test/java/org/mozilla/focus/toolbar/ToolbarTextTest.kt
- app/src/test/java/org/mozilla/focus/utils/ToastManagerTest.kt
- build.gradle
- I added unit tests to changed code that won't soon be removed by components implementations (e.g. webView)
- Not user facing
> Closes #72: Upgrade to SDK 28

- app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxWebView.kt
- app/src/main/java/org/mozilla/focus/FocusApplication.kt
- app/src/main/java/org/mozilla/focus/MainActivity.kt
- app/src/main/java/org/mozilla/focus/MainActivityViewModel.kt
- app/src/main/java/org/mozilla/focus/architecture/ViewModelFactory.kt
- app/src/main/java/org/mozilla/focus/browser/BrowserFragment.kt
- app/src/main/java/org/mozilla/focus/browser/BrowserViewModel.kt
- app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt
- app/src/main/java/org/mozilla/focus/session/SessionRepo.kt
- app/src/main/java/org/mozilla/focus/toolbar/BrowserAppBarLayoutController.kt
- app/src/main/java/org/mozilla/focus/toolbar/BrowserAppBarViewModel.kt
- app/src/main/java/org/mozilla/focus/widget/ServiceLocator.kt
- app/src/main/res/layout/fragment_browser.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/org/mozilla/focus/MainActivityViewModelTest.kt
- app/src/test/java/org/mozilla/focus/browser/BrowserViewModelTest.kt
- app/src/test/java/org/mozilla/focus/browser/FullscreenCallbacksTest.kt
- app/src/test/java/org/mozilla/focus/session/SessionRepoTest.kt
- app/src/test/java/org/mozilla/focus/toolbar/BrowserAppBarViewModelTest.kt
Issue #218 and #219 are the two release blockers for version 1.3: this PR takes the patches, which have already been reviewed and landed on master, and uplifts them to the `releases/v1.3` branch.
The code here (probably) doesn't need a re-review: please review that I got all the right patches and issues to uplift though. Note that the release should be complete after this: it will contain the right version number and all the remaining patches.
> No issue: uplift release blocker fixes to 1.3 release branch

- README.md
> No issue: add codecov badge to readme.

- .github/ISSUE_TEMPLATE/---bug-report.md
FF versions were a request from @athomasmoz
> Ni mcomella issue template

- .github/ISSUE_TEMPLATE/---bug-report.md
> No issue: fix typo in issue template.

- .github/ISSUE_TEMPLATE/---chore.md
- .github/ISSUE_TEMPLATE/---feature-request.md
> No issue: update issue labels (chore, auto-label features)

- CHANGELOG.md
- app/src/main/java/org/mozilla/focus/MainActivity.kt
- app/src/main/java/org/mozilla/focus/MainActivityIntentResponder.kt
- app/src/main/java/org/mozilla/focus/session/SessionRestorer.kt
- app/src/main/java/org/mozilla/focus/session/SessionRestorerStorage.kt
- app/src/main/java/org/mozilla/focus/settings/UserClearDataEventObserver.kt
- app/src/test/java/org/mozilla/focus/MainActivityIntentResponderTest.kt
- app/src/test/java/org/mozilla/focus/session/SessionRestorerStorageTest.kt
- app/src/test/java/org/mozilla/focus/session/SessionRestorerTest.kt
- app/src/test/java/org/mozilla/focus/settings/UserClearDataEventObserverTest.kt
> Closes #186: Add SessionRestore

- CHANGELOG.md
> Update changelog with v1.3 release date

- app/build.gradle
- build.gradle
- tools/sign_release.sh
- Nothing to test
- Should be unaffected
> Closes #262: integrate Mozilla gradle plugin

- .taskcluster.yml
Like https://github.com/mozilla-mobile/firefox-tv/pull/1999 – we don't run TC but I don't want to forget to update this later
> No issue: TC for collaborators only.

- tools/sign_release.sh
refs: #287
No idea if this needs one.
No Java/Kotlin/UI changes. Not sure why CI is failing.
> Issue #287: zip align after signing release

- tools/sign_release.sh
> Closes #287: fixes signed builds crashing when opening any website

- app/lint.xml
- tools/sign_release.sh
> No issue cherry pick 1.3.1

- CHANGELOG.md
- app/build.gradle
> No issue v1.3.1 version bump

- .github/ISSUE_TEMPLATE/---bug-report.md
> No issue: Add Echo Show 5 to device list

- CHANGELOG.md
> No issue: add v1.3.1 to changelog

- docs/device_reference.md
I had to collect some of these during a recent story, figured I should update the doc while doing so.
> No issue: partial update to device_reference for ES5

- app/build.gradle
- app/lint.xml
- app/src/main/assets/licenses.html
- app/src/main/java/org/mozilla/focus/widget/AccessibleGridLayoutManager.kt
> Closes #300: Fix lint errors

- app/src/main/AndroidManifest.xml
> Closes #306: add media session permission

- app/build.gradle
> No issue: bump version to v1.4.

- README.md
> Remove IRC reference in README

- app/build.gradle
> Bump version to v1.5

- app/proguard-rules.pro
> Closes #331: Update pro-guard setting for glean

- CHANGELOG.md
> No issue: Update changelog for v1.4 and v1.5 releases.
